### ISSUE TITLE
I encountered some new problems

### ISSUE THREAD

**Issue by paranoid-27** [ssg-research/WAFFLE#3]
last week，I reloaded the code，but I encountered some new problems. I tried to run the FL model with watermarking by using "python main.py --config_file configurations/waffle_experiments/cifar10/1.ini --experiment training", then occurred error：num_samples should be a positive integer value, but got num_samples=0. More details are as follow：
      
![image](https://user-images.githubusercontent.com/24192310/140917534-9e6196ef-531a-4af5-b9b9-3bc0920247f7.png)
![image](https://user-images.githubusercontent.com/24192310/140919647-2d1e9b6f-12c3-43dc-91d3-271cdad51f12.png)

         And I checked the configuration file in “configurations/waffle_experiments/cifar10/1.ini”，I found the path “watermark_dataset_save_path =  ./data/datasets/CWAFFLE/”  doesn't exist，I am wondering if the relevant files are missing.I hope to receive your reply soon. Have a nice day!

**Comment by bussfromspace** [comment]
Hi,
It looks like it cannot find the /data/datasets/CWAFFLE/. "src/data/datasets/" folder contains different watermark sets and I modified them last week. Could you pull the latest changes and run the experiment again?

**Comment by paranoid-27** [comment]
> Hi, It looks like it cannot find the /data/datasets/CWAFFLE/. "src/data/datasets/" folder contains different watermark sets and I modified them last week. Could you pull the latest changes and run the experiment again?

Last time,I just reloaded a part of codes，I was too careless.Thank you for your reply！！！
