### ISSUE TITLE
CUDA mapping error

### ISSUE THREAD

**Issue by ParthMandaliya** [ssg-research/WAFFLE#4]
While executing the following command, I am getting CUDA mapping error:
```python main.py --config_file configurations/baseline_experiments/mnist/1.ini --experiment training```

The error is as follows:
```
    response = eval(cmd)(*args, **kwargs)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```
Here are some details about my machine:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
And here are some details about CUDA and cuDNN card I am using:
NVIDIA: RTX 3060 (mobile)
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
```

Let me know if you need any more information.

**Comment by bussfromspace** [comment]
Hi,
Could you send me PyTorch and CUDA versions? 
Sometimes the mismatch between cuda and torch versions (you can check here https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver) might produce this error. 
Could you also try to reproduce the results again by using 
`torch.backends.cudnn.enabled = False`

**Comment by ParthMandaliya** [comment]
@bussfromspace I downloaded Pytorch using conda environment file from PyTorch website.
Below is the detail you asked for:
```
Name: torch
Version: 1.11.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/parth/anaconda3/lib/python3.9/site-packages
Requires: typing_extensions
Required-by: torchvision, torchaudio
```
and here is the torchvision details:
```
Name: torchvision
Version: 0.12.0
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: /home/parth/anaconda3/lib/python3.9/site-packages
Requires: typing_extensions, numpy, requests, torch, pillow
Required-by: 
```
